version: "2"

volumes:
  pgdata:
    driver: local

services:
  app:
    image: postgres-go
    build: .
    environment:
        PORT: 80
        DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 8080:80
  postgres:
    image: postgres:latest
    container_name: postgres
    privileged: true
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data